"""add terminal settings to user model

Revision ID: 05804235af5d
Revises: add_user_auth
Create Date: 2025-10-19 19:44:51.594509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05804235af5d'
down_revision: Union[str, None] = 'add_user_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terminal_settings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terminal_settings')
    # ### end Alembic commands ###
