"""Initial migration

Revision ID: 0f11d42a83e3
Revises: 
Create Date: 2025-10-18 10:26:26.633475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f11d42a83e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssh_clients_host'), 'ssh_clients', ['host'], unique=False)
    op.create_index(op.f('ix_ssh_clients_id'), 'ssh_clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssh_clients_id'), table_name='ssh_clients')
    op.drop_index(op.f('ix_ssh_clients_host'), table_name='ssh_clients')
    op.drop_table('ssh_clients')
    # ### end Alembic commands ###
