"""add user_id to ssh_clients

Revision ID: bc484cccebb4
Revises: c367fdb753c8
Create Date: 2025-11-29 10:32:29.499940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc484cccebb4'
down_revision: Union[str, None] = 'c367fdb753c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('ssh_clients', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # 2. Update existing rows with a default user_id (e.g., 1)
    # We use a raw SQL execution for this
    op.execute("UPDATE ssh_clients SET user_id = 1 WHERE user_id IS NULL")
    
    # 3. Alter column to be not null
    op.alter_column('ssh_clients', 'user_id', nullable=False)
    
    # 4. Create foreign key
    op.create_foreign_key(None, 'ssh_clients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ssh_clients', type_='foreignkey')
    op.drop_column('ssh_clients', 'user_id')
    # ### end Alembic commands ###
